# vi mode
bindkey -v
export KEYTIMEOUT=1
export PS1=" %2~ %# "

export DOTFILES=$HOME/github/zperrault/dotfiles
export RC_FILES=$DOTFILES/configs/zsh/rc
export SECRETS=$DOTFILES/secrets/zsh

for file in $RC_FILES/*; do
  source "$file"
done

for file in $SECRETS/*; do
  source "$file"
done

export EDITOR=nvim
if [ -e /Users/zach/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/zach/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
