# vi mode
bindkey -v
export KEYTIMEOUT=1
export PS1=" %2~ %# "

export DOTFILES=$HOME/github/zperrault/dotfiles
export RC_FILES=$DOTFILES/configs/zsh/rc

for file in $RC_FILES/*; do
  source "$file"
done

export EDITOR=nvim
