custom-commands:
  - name: mine
    help: Show issues assigned and not completed
    script: | 
      {{jira}} list --query "(status='In Progress' OR status='To Do' OR status='Code Review') AND assignee = currentuser()"
  - name: branch
    help: Checkout a new branch for the selected issue
    args:
      - name: ISSUE
        help: The issue to make a new branch for
        required: true
    script: |
      git checkout -b $({{jira}} view {{args.ISSUE}} --template git-branch)
  - name: current
    help: Get the current issue from the git branch
    script: |
      git branch | grep \* | cut -d ' ' -f2 | cut -d '-' -f1,2
