#!/usr/bin/env osascript -l JavaScript

function findEntityByName(entity) {
  return function (name) {
    const things = new Application('Things3')
    return things[entity]().find(e => e.name().toLowerCase().includes(name.toLowerCase()))
  }
}

const DEFAULT_FORMAT = 'name'
function print(entity, format = DEFAULT_FORMAT) {
  console.log(
    format.split(',').map(path =>
      path.split('.').reduce((acc, key) => acc && acc[key] && acc[key](), entity)
    ).join('\t')
  )
}

function findAndPrintToDosInEntityWithName(entity) {
  return function (name, ...args) {
    findEntityByName(entity)(name).toDos().forEach(toDo => {
      print(toDo, ...args)
    })
  }
}
function printEntities(entity) {
  return function (...args) {
    Application('Things3')[entity]().forEach(e => print(e, ...args))
  }
}


const commands = {
  inbox: (...args) => findAndPrintToDosInEntityWithName('lists')('inbox', ...args),
  today: (...args) => findAndPrintToDosInEntityWithName('lists')('today', ...args),
  lists: printEntities('lists'),
  list: findAndPrintToDosInEntityWithName('lists'),
  projects: printEntities('projects'),
  project: findAndPrintToDosInEntityWithName('projects'),
  area: findAndPrintToDosInEntityWithName('areas'),
  areas: printEntities('areas'),
}

function run(argv) {
  const [command, ...others] = argv
  commands[command](...others)
}
