#!/usr/bin/env osascript -l JavaScript

function findListByName(name) {
  const things = new Application('Things3')
  return things.lists().find(list => list.name().toLowerCase() === name.toLowerCase())
}

function print(entity, format) {
  console.log(
    format.split(',').map(path =>
      path.split('.').reduce((acc, key) => acc && acc[key] && acc[key](), entity)
    ).join('\t')
  )
}

function list(name) {
  findListByName(name).toDos().forEach(toDo => {
    print(toDo, 'status,name,project.name')
  })
}

function run(argv) {
  const [command, ...others] = argv
  switch (command) {
    case 'list':
      return list(...others)
  }
}
